services:
  postgres:
    container_name: ecom_ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: eltonmessias
      POSTGRES_PASSWORD: messias8669
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ecommerce-ms-net
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ecom_ms_mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eltonmessias
      - MONGO_INITDB_ROOT_PASSWORD=messias8669

  mongo-express:
    image: mongo-express:latest
    container_name: ecom_ms_mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=eltonmessias
      - ME_CONFIG_MONGODB_ADMINPASSWORD=messias8669
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH=false

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ecom_ms_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - ecommerce-ms-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ecom_ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - ecommerce-ms-net

  mail-dev:
    container_name: ecom_ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  ecommerce-ms-net:
    driver: bridge


volumes:
  postgres:
  pgadmin:
  mongo: