services:
  postgres:
    container_name: ecom_ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: eltonmessias
      POSTGRES_PASSWORD: messias8669
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ecommerce-ms-net
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ecom_ms_mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eltonmessias
      - MONGO_INITDB_ROOT_PASSWORD=messias8669

  mongo-express:
    image: mongo-express:latest
    container_name: ecom_ms_mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=eltonmessias
      - ME_CONFIG_MONGODB_ADMINPASSWORD=messias8669
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH=false





networks:
  ecommerce-ms-net:
    driver: bridge


volumes:
  postgres:
  pgadmin:
  mongo: